# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Learnbioinfo.com
subtitle: Bioinformatics made simple
email: abdullah.daoud@live.acibadem.edu.tr
description: A comprehensive resource for learning biostatistics and bioinformatics. # this means to ignore newlines until "baseurl:"
  
# Don't forget to uncomment the 2 lines below.
# the subpath of your site, e.g. /blog
url: "https://learnbioinfo.com" # the base hostname & protocol for your site, e.g. http://example.com
locale: "en-US"
logo: "/assets/images/88x104.png"
search: true


# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
  - jekyll-include-cache

include: 
  - "_pages"
  - "_lessons"
  - "_includes"

collections_dir: site-collections
collections:
  biostatistics:
    output: true
    permalink: /:collection/:path/
  bioinformatics:
    output: true
    permalink: /:collection/:path/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
